include_directories(${CMAKE_CURRENT_LIST_DIR})

set(
        ARCS_LIBS_files
        ${CMAKE_CURRENT_LIST_DIR}/ActivationFunctions.cc
        ${CMAKE_CURRENT_LIST_DIR}/ActivationFunctions.hh
        ${CMAKE_CURRENT_LIST_DIR}/ArcTangent.cc
        ${CMAKE_CURRENT_LIST_DIR}/ArcTangent.hh
        ${CMAKE_CURRENT_LIST_DIR}/BatchProcessor.cc
        ${CMAKE_CURRENT_LIST_DIR}/BatchProcessor.hh
        ${CMAKE_CURRENT_LIST_DIR}/ChirpGenerator.cc
        ${CMAKE_CURRENT_LIST_DIR}/ChirpGenerator.hh
        ${CMAKE_CURRENT_LIST_DIR}/ClassBase.cc
        ${CMAKE_CURRENT_LIST_DIR}/ClassBase.hh
        ${CMAKE_CURRENT_LIST_DIR}/ClassTemplate.cc
        ${CMAKE_CURRENT_LIST_DIR}/ClassTemplate.hh
        ${CMAKE_CURRENT_LIST_DIR}/CPUSettings.cc
        ${CMAKE_CURRENT_LIST_DIR}/CPUSettings.hh
        ${CMAKE_CURRENT_LIST_DIR}/CsvManipulator.cc
        ${CMAKE_CURRENT_LIST_DIR}/CsvManipulator.hh
        ${CMAKE_CURRENT_LIST_DIR}/CuiPlot.cc
        ${CMAKE_CURRENT_LIST_DIR}/CuiPlot.hh
        ${CMAKE_CURRENT_LIST_DIR}/CurrencyDatasets.cc
        ${CMAKE_CURRENT_LIST_DIR}/CurrencyDatasets.hh
        ${CMAKE_CURRENT_LIST_DIR}/DataStorage.cc
        ${CMAKE_CURRENT_LIST_DIR}/DataStorage.hh
        ${CMAKE_CURRENT_LIST_DIR}/DeadBand.cc
        ${CMAKE_CURRENT_LIST_DIR}/DeadBand.hh
        ${CMAKE_CURRENT_LIST_DIR}/Differentiator.cc
        ${CMAKE_CURRENT_LIST_DIR}/Differentiator.hh
        ${CMAKE_CURRENT_LIST_DIR}/Differentiator2.cc
        ${CMAKE_CURRENT_LIST_DIR}/Differentiator2.hh
        ${CMAKE_CURRENT_LIST_DIR}/Discret.cc
        ${CMAKE_CURRENT_LIST_DIR}/Discret.hh
        ${CMAKE_CURRENT_LIST_DIR}/DisturbanceObsrv.cc
        ${CMAKE_CURRENT_LIST_DIR}/DisturbanceObsrv.hh
        ${CMAKE_CURRENT_LIST_DIR}/FeedforwardNeuralNet3.cc
        ${CMAKE_CURRENT_LIST_DIR}/FeedforwardNeuralNet3.hh
        ${CMAKE_CURRENT_LIST_DIR}/FixedAverage.cc
        ${CMAKE_CURRENT_LIST_DIR}/FixedAverage.hh
        ${CMAKE_CURRENT_LIST_DIR}/FRAgenerator.cc
        ${CMAKE_CURRENT_LIST_DIR}/FRAgenerator.hh
        ${CMAKE_CURRENT_LIST_DIR}/FrameFontSmall.cc
        ${CMAKE_CURRENT_LIST_DIR}/FrameFontSmall.hh
        ${CMAKE_CURRENT_LIST_DIR}/FrameGraphics.cc
        ${CMAKE_CURRENT_LIST_DIR}/FrameGraphics.hh
        ${CMAKE_CURRENT_LIST_DIR}/FunctionBase.cc
        ${CMAKE_CURRENT_LIST_DIR}/FunctionBase.hh
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter.cc
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter.hh
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter2.cc
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter2.hh
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter_Tmp.cc
        ${CMAKE_CURRENT_LIST_DIR}/HighPassFilter_Tmp.hh
        ${CMAKE_CURRENT_LIST_DIR}/HysteresisComparator.cc
        ${CMAKE_CURRENT_LIST_DIR}/HysteresisComparator.hh
        ${CMAKE_CURRENT_LIST_DIR}/I-P-I-Pcontroller.cc
        ${CMAKE_CURRENT_LIST_DIR}/I-P-I-Pcontroller.hh
        ${CMAKE_CURRENT_LIST_DIR}/I-PDcontroller.cc
        ${CMAKE_CURRENT_LIST_DIR}/I-PDcontroller.hh
        ${CMAKE_CURRENT_LIST_DIR}/Integrator.cc
        ${CMAKE_CURRENT_LIST_DIR}/Integrator.hh
        ${CMAKE_CURRENT_LIST_DIR}/Integrator2.cc
        ${CMAKE_CURRENT_LIST_DIR}/Integrator2.hh
        ${CMAKE_CURRENT_LIST_DIR}/IrisClassDatasets.cc
        ${CMAKE_CURRENT_LIST_DIR}/IrisClassDatasets.hh
        ${CMAKE_CURRENT_LIST_DIR}/IrisDatasets.cc
        ${CMAKE_CURRENT_LIST_DIR}/IrisDatasets.hh
        ${CMAKE_CURRENT_LIST_DIR}/Limiter.cc
        ${CMAKE_CURRENT_LIST_DIR}/Limiter.hh
        ${CMAKE_CURRENT_LIST_DIR}/LinuxCommander.cc
        ${CMAKE_CURRENT_LIST_DIR}/LinuxCommander.hh
        ${CMAKE_CURRENT_LIST_DIR}/LoadsideDistObsrv.cc
        ${CMAKE_CURRENT_LIST_DIR}/LoadsideDistObsrv.hh
        ${CMAKE_CURRENT_LIST_DIR}/LowPassFilter.cc
        ${CMAKE_CURRENT_LIST_DIR}/LowPassFilter.hh
        ${CMAKE_CURRENT_LIST_DIR}/LowPassFilter2.cc
        ${CMAKE_CURRENT_LIST_DIR}/LowPassFilter2.hh
        ${CMAKE_CURRENT_LIST_DIR}/Matrix.cc
        ${CMAKE_CURRENT_LIST_DIR}/Matrix.hh
        ${CMAKE_CURRENT_LIST_DIR}/MotorFrameTransform.cc
        ${CMAKE_CURRENT_LIST_DIR}/MotorFrameTransform.hh
        ${CMAKE_CURRENT_LIST_DIR}/MotorParamDef.hh
        ${CMAKE_CURRENT_LIST_DIR}/MotorSimulator.cc
        ${CMAKE_CURRENT_LIST_DIR}/MotorSimulator.hh
        ${CMAKE_CURRENT_LIST_DIR}/MotorSimulators.cc
        ${CMAKE_CURRENT_LIST_DIR}/MotorSimulators.hh
        ${CMAKE_CURRENT_LIST_DIR}/MovingAverage.cc
        ${CMAKE_CURRENT_LIST_DIR}/MovingAverage.hh
        ${CMAKE_CURRENT_LIST_DIR}/NeuralNetParamDef.hh
        ${CMAKE_CURRENT_LIST_DIR}/NotchFilter.cc
        ${CMAKE_CURRENT_LIST_DIR}/NotchFilter.hh
        ${CMAKE_CURRENT_LIST_DIR}/Observer.cc
        ${CMAKE_CURRENT_LIST_DIR}/Observer.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-2826CV.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-2826CV.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3133.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3133.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3180.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3180.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3340.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3340.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3343A.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-3343A.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-6205C.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-6205C.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCI-46610x.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCI-46610x.hh
        ${CMAKE_CURRENT_LIST_DIR}/PCIe-AC01.cc
        ${CMAKE_CURRENT_LIST_DIR}/PCIe-AC01.hh
        ${CMAKE_CURRENT_LIST_DIR}/PDcontroller.cc
        ${CMAKE_CURRENT_LIST_DIR}/PDcontroller.hh
        ${CMAKE_CURRENT_LIST_DIR}/PhaseLeadLag.cc
        ${CMAKE_CURRENT_LIST_DIR}/PhaseLeadLag.hh
        ${CMAKE_CURRENT_LIST_DIR}/PIcontroller.cc
        ${CMAKE_CURRENT_LIST_DIR}/PIcontroller.hh
        ${CMAKE_CURRENT_LIST_DIR}/PIDcontroller.cc
        ${CMAKE_CURRENT_LIST_DIR}/PIDcontroller.hh
        ${CMAKE_CURRENT_LIST_DIR}/RandomGenerator.cc
        ${CMAKE_CURRENT_LIST_DIR}/RandomGenerator.hh
        ${CMAKE_CURRENT_LIST_DIR}/RecurrentNeuralLayer.cc
        ${CMAKE_CURRENT_LIST_DIR}/RecurrentNeuralLayer.hh
        ${CMAKE_CURRENT_LIST_DIR}/RingBuffer.cc
        ${CMAKE_CURRENT_LIST_DIR}/RingBuffer.hh
        ${CMAKE_CURRENT_LIST_DIR}/RPi2GPIO.cc
        ${CMAKE_CURRENT_LIST_DIR}/RPi2GPIO.hh
        ${CMAKE_CURRENT_LIST_DIR}/SA2-RasPi2.cc
        ${CMAKE_CURRENT_LIST_DIR}/SA2-RasPi2.hh
        ${CMAKE_CURRENT_LIST_DIR}/SFthread.cc
        ${CMAKE_CURRENT_LIST_DIR}/SFthread.hh
        ${CMAKE_CURRENT_LIST_DIR}/Shuffle.cc
        ${CMAKE_CURRENT_LIST_DIR}/Shuffle.hh
        ${CMAKE_CURRENT_LIST_DIR}/Sigmoid.cc
        ${CMAKE_CURRENT_LIST_DIR}/Sigmoid.hh
        ${CMAKE_CURRENT_LIST_DIR}/Signum.cc
        ${CMAKE_CURRENT_LIST_DIR}/Signum.hh
        ${CMAKE_CURRENT_LIST_DIR}/SimplePerceptron.cc
        ${CMAKE_CURRENT_LIST_DIR}/SimplePerceptron.hh
        ${CMAKE_CURRENT_LIST_DIR}/SingleLayerPerceptron.cc
        ${CMAKE_CURRENT_LIST_DIR}/SingleLayerPerceptron.hh
        ${CMAKE_CURRENT_LIST_DIR}/SpeedCalculator.cc
        ${CMAKE_CURRENT_LIST_DIR}/SpeedCalculator.hh
        ${CMAKE_CURRENT_LIST_DIR}/SquareWave.cc
        ${CMAKE_CURRENT_LIST_DIR}/SquareWave.hh
        ${CMAKE_CURRENT_LIST_DIR}/StairsWave.cc
        ${CMAKE_CURRENT_LIST_DIR}/StairsWave.hh
        ${CMAKE_CURRENT_LIST_DIR}/StateSpaceSystem.cc
        ${CMAKE_CURRENT_LIST_DIR}/StateSpaceSystem.hh
        ${CMAKE_CURRENT_LIST_DIR}/Statistics.cc
        ${CMAKE_CURRENT_LIST_DIR}/Statistics.hh
        ${CMAKE_CURRENT_LIST_DIR}/StepWave.cc
        ${CMAKE_CURRENT_LIST_DIR}/StepWave.hh
        ${CMAKE_CURRENT_LIST_DIR}/TimeDelay.cc
        ${CMAKE_CURRENT_LIST_DIR}/TimeDelay.hh
        ${CMAKE_CURRENT_LIST_DIR}/TransferFunction.cc
        ${CMAKE_CURRENT_LIST_DIR}/TransferFunction.hh
        ${CMAKE_CURRENT_LIST_DIR}/TriangleWave.cc
        ${CMAKE_CURRENT_LIST_DIR}/TriangleWave.hh
        ${CMAKE_CURRENT_LIST_DIR}/TrqbsdVelocityObsrv.cc
        ${CMAKE_CURRENT_LIST_DIR}/TrqbsdVelocityObsrv.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaParamDef.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaSimulator.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaSimulator.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaSimulators.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaSimulators.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateDistObsrv.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateDistObsrv.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateFeedback.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateFeedback.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateObsrv.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoInertiaStateObsrv.hh
        ${CMAKE_CURRENT_LIST_DIR}/TwoStepWave.cc
        ${CMAKE_CURRENT_LIST_DIR}/TwoStepWave.hh
        ${CMAKE_CURRENT_LIST_DIR}/UDPReceiver.cc
        ${CMAKE_CURRENT_LIST_DIR}/UDPReceiver.hh
        ${CMAKE_CURRENT_LIST_DIR}/UDPTransmitter.cc
        ${CMAKE_CURRENT_LIST_DIR}/UDPTransmitter.hh
        ${CMAKE_CURRENT_LIST_DIR}/WEF-6A.cc
        ${CMAKE_CURRENT_LIST_DIR}/WEF-6A.hh
)