# modディレクトリ用Makefile
# 2016/11/16

# ディレクトリ内すべてコンパイル＆リンク
# モジュールを追加した場合には下記に適宜追加せよ
all:
	@cd pcie_ac01; $(MAKE) --no-print-directory

# 掃除
# モジュールを追加した場合には下記に適宜追加せよ
.PHONY: clean
clean:
	@$(MAKE) --no-print-directory clean -C ./pcie_ac01

